Ambe.Frontend/Ambe.Frontend/Models/Entidades/Personas.cs
using System.ComponentModel.DataAnnotations;

namespace Ambe.Frontend.Models.Entidades
{
    public class Personas
    {
        public int IdPersona { get; set; }

        public int IdTipoPersona { get; set; }

        public int IdInstituto { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Solo se permiten letras.")]
        public string PrimerNombre { get; set; } = null!;

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Solo se permiten letras.")]
        public string SegundoNombre { get; set; } = null!;

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Solo se permiten letras.")]
        public string PrimerApellido { get; set; } = null!;

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Solo se permiten letras.")]
        public string SegundoApellido { get; set; } = null!;

        public DateTime FechaNacimiento { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Solo se permiten letras.")]
        public string Genero { get; set; } = null!;

        public string CreadoPor { get; set; } = null!;

        public DateTime FechaCreacion { get; set; }

        public string ModificadoPor { get; set; } = null!;

        public DateTime FechaModificacion { get; set; }

        public string Estado { get; set; } = null!;

        public string NombreCompleto => $"{PrimerNombre} {PrimerApellido}";
    }
}

Ambe.Frontend/Ambe.Frontend/Models/PersonaViewModel.cs
namespace Ambe.Frontend.Models
{
    public class PersonaViewModel
    {
        public int IdTipoPersona { get; set; }

        public int IdInstituto { get; set; }

        public string PrimerNombre { get; set; } = null!;

        public string SegundoNombre { get; set; } = null!;

        public string PrimerApellido { get; set; } = null!;

        public string SegundoApellido { get; set; } = null!;

        public DateTime FechaNacimiento { get; set; } 

        public string Genero { get; set; } = null!;

        public string Usuario { get; set; } = null!;

        public string NombreUsuario { get; set; } = null!;

        public string CorreoElectronico { get; set; } = null!;

        public string Contraseña { get; set; } = null!;

        public string Estado { get; set; } = null!;

        public int IdRol { get; set; }

        public DateTime FechaUltimaConexion { get; set; }

        public string CreadoPor { get; set; } = null!;

        public string ModificadoPor { get; set; } = null!;
    }
}

Ambe.Frontend/Ambe.Frontend/Controllers/PersonasController.cs
using Ambe.Frontend.Models;
using Ambe.Frontend.Models.Entidades;
using Ambe.Frontend.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Ambe.Frontend.Controllers
{
    public class PersonasController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly IBitacoraService _bitacora;
        private readonly IServicioPersonas _personas;

        public PersonasController(IHttpClientFactory httpClientFactory, IBitacoraService bitacoraService, IServicioPersonas personas)
        {
            _httpClient = httpClientFactory.CreateClient();
            _httpClient.BaseAddress = new Uri("https://ambetest.somee.com");
            _bitacora = bitacoraService;
            _personas = personas;
        }

        public async Task<IActionResult> Index()
        {
            var personas = await _personas.GetPersonasAsync();
            var tiposPersona = await _personas.GetTiposPersonaAsync();

            var personasDTO = personas.Select(p => new PersonaDTO
            {
                IdPersona = p.IdPersona,
                IdTipoPersona = p.IdTipoPersona,
                Descripcion = tiposPersona.FirstOrDefault(tp => tp.IdTipoPersona == p.IdTipoPersona)?.TipoPersona ?? "Desconocido",
                NombreCompleto = p.PrimerNombre + " " + p.SegundoNombre,
                FechaCreacion = p.FechaCreacion,
                Estado = p.Estado
            }).ToList();

            return View(personasDTO);

        }

        public async Task<IActionResult> VerContacto(int idPersona)
        {           
            var contactos = await _personas.GetContactosAsync(idPersona);
            if (contactos == null || !contactos.Any())
            {
                ViewBag.Message = "No se encontraron contactos para esta persona.";
            }
            return View(contactos);
        }
    }
}

Ambe.Frontend/Ambe.Frontend/Views/Personas/Index.cshtml
@model IEnumerable<Ambe.Frontend.Models.PersonaDTO>
@{
    ViewData["Title"] = "Index";
}

@section Estilos {
    <link href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" rel="stylesheet" />
}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if (TempData["AlertMessage"] != null)
{
    <script>
        $(function () {
            Swal.fire({
                title: '¡Éxito!',
                text: '@TempData["AlertMessage"]',
                icon: 'success',
                confirmButtonText: 'Aceptar'
            });
        });
    </script>
}

@if (TempData["ErrorMessage"] != null)
{
    <script>
        $(function () {
            Swal.fire({
                title: '¡Error!',
                text: '@TempData["ErrorMessage"]',
                icon: 'warning',
                confirmButtonText: 'Aceptar'
            });
        });
    </script>
}



<div class="col-md-12">
    <div class="card">
        <div class="card-header text-center bg-custom">
            <div class="card-header text-center">
                <img src="/images/ramgar.png" style="width: 75px; height: auto; border-radius: 50%; object-fit: cover;" />
            </div>
        </div>
        <div class="card-body">
            <h5 class="card-title text-center">Lista de Personas</h5>
            <table id="persona" class="table table-hover table-responsive table-striped">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Tipo</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Fecha de creacion</th>
                        <th scope="col">Estado</th>                        
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row">@item.IdPersona</th>
                            <td>@Html.DisplayFor(modelItem => item.Descripcion)</td>
                            <td>@Html.DisplayFor(modelItem => item.NombreCompleto)</td>
                            <td>@Html.DisplayFor(modelItem => item.FechaCreacion)</td>
                            <td>@Html.DisplayFor(modelItem => item.Estado)</td>
                           
                            <td>                                
                                <form asp-controller="Personas" asp-action="VerContacto" method="get">
                                    <input type="hidden" name="idPersona" value="@item.IdPersona" />
                                    <button type="submit" class="btn btn-outline-success btn-sm"><i class="oi oi-book"></i></button>
                                </form>
                                <button data-id="@item.IdPersona" class="btn btn-outline-danger btn-sm deleteItem">
                                    <i class="oi oi-trash"></i>
                                </button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<partial name="_MostrarModal" />


@section Scripts {

    <partial name="_ValidationScriptsPartial" />

    <script src="~/js/showmodal.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#persona').DataTable({
                "language": {
                    url: "https://cdn.datatables.net/plug-ins/1.11.5/i18n/es-ES.json"
                },
            });
        });
    </script>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const deleteButtons = document.querySelectorAll('.deleteItem');

            deleteButtons.forEach(button => {
                button.addEventListener('click', function (event) {
                    event.preventDefault();

                    const patientId = this.getAttribute('data-id');


                    Swal.fire({
                        title: '¿Estás seguro?',
                        text: "¡No podrás revertir esto!",
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Sí, eliminarlo',
                        cancelButtonText: 'Cancelar'
                    }).then((result) => {
                        if (result.isConfirmed) {

                            window.location.href = '/Personas/Delete/' + patientId;
                        }
                    });
                });
            });
        });
    </script>

}

Ambe.Frontend/Ambe.Frontend/Views/Personas/VerContacto.cshtml
@model IEnumerable<Ambe.Frontend.Models.Entidades.Contactos> 

@{
    ViewData["Title"] = "Lista de Contactos";
}




<h2>Contactos de la Persona</h2>

@if (ViewBag.Message != null)
{
    <div class="alert alert-warning">@ViewBag.Message</div>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Direccion</th>
                <th>Email</th>
                <th>Teléfono</th>
                <th>Latitud</th>
                <th>Longitud</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var contacto in Model)
            {
                <tr>
                    <td>@contacto.Direccion</td>
                    <td>@contacto.Email</td>
                    <td>@contacto.Telefono</td>
                    <td>@contacto.Latitud</td>
                    <td>@contacto.Longitud</td>
                </tr>
            }
        </tbody>
    </table>
}

<button type="button" class="btn btn-sm btn-primary" onclick="window.history.back();">
    <i class="oi oi-arrow-thick-left"></i> Regresar
</button>