Ambe.Frontend/Ambe.Frontend/Models/Entidades/Parametros.cs
namespace Ambe.Frontend.Models.Entidades
{
    public class Parametros
    {
        public int IdParametro { get; set; }

        public string Parametro { get; set; } = null!;

        public string Valor { get; set; } = null!;

        public int IdUsuario { get; set; }
    }
}

Ambe.Frontend/Ambe.Frontend/Controllers/ParametrosController.cs
using Ambe.Frontend.Models.Entidades;
using Ambe.Frontend.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace Ambe.Frontend.Controllers
{
    public class ParametrosController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly IBitacoraService _bitacora;

        public ParametrosController(IHttpClientFactory httpClientFactory, IBitacoraService bitacoraService)
        {
            _httpClient = httpClientFactory.CreateClient();
            _httpClient.BaseAddress = new Uri("https://ambetest.somee.com");
            _bitacora = bitacoraService;
        }
        public async Task<IActionResult> Index()
        {
            var response = await _httpClient.GetAsync("/api/Parametros");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var parametros = JsonConvert.DeserializeObject<IEnumerable<Parametros>>(content);
                return View("Index", parametros);
            }
            return View(new List<Parametros>());
        }

        public async Task<IActionResult> Create()
        {
            var email = Uri.EscapeDataString(User.Identity!.Name!);
            var userResponse = await _httpClient.GetAsync($"/api/Usuarios/email/{email}");
            var usuarioJson = await userResponse.Content.ReadAsStringAsync();
            var user = JsonConvert.DeserializeObject<Usuarios>(usuarioJson);

            Parametros parametros = new()
            {
                IdUsuario = user!.IdUsuario
            };
            return View(parametros);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Parametros parametros)
        {
            if (ModelState.IsValid)
            {
                var json = JsonConvert.SerializeObject(parametros);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                var response = await _httpClient.PostAsync("/api/Parametros/", content);

                if (response.IsSuccessStatusCode)
                {
                    TempData["AlertMessage"] = "Parametro creado exitosamente!!!";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Error al crear el parametro.");
                    TempData["ErrorMessage"] = "Ocurrió un error al intentar crear el parametro!!!";
                }
            }
            else
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
                TempData["ModelErrors"] = string.Join("\n", errors);
            }
            return View(parametros);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var response = await _httpClient.GetAsync($"/api/Parametros/{id}");
            if (!response.IsSuccessStatusCode)
            {
                TempData["ErrorMessage"] = "Error al obtener parametro.";
                return RedirectToAction("Index");
            }

            var jsonString = await response.Content.ReadAsStringAsync();
            var parametros = JsonConvert.DeserializeObject<Parametros>(jsonString);

            return View(parametros);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Parametros parametros)
        {
            if (ModelState.IsValid)
            {
                var json = JsonConvert.SerializeObject(parametros);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                var response = await _httpClient.PutAsync($"/api/Parametros/{id}", content);
                if (response.IsSuccessStatusCode)
                {
                    TempData["AlertMessage"] = "Parametro actualizado exitosamente!!!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["ErrorMessage"] = "Error al actualizar el parametro.";
                    return RedirectToAction("Index");
                }
            }
            return View(parametros);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _httpClient.DeleteAsync($"/api/Parametros/{id}");

            if (response.IsSuccessStatusCode)
            {
                TempData["AlertMessage"] = "Parametro eliminado exitosamente!!!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Error"] = "Error al eliminar el parametro.";
                return RedirectToAction("Index");
            }
        }
    }
}

Ambe.Frontend/Ambe.Frontend/Views/Parametros/Create.cshtml
@model Ambe.Frontend.Models.Entidades.Parametros
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/ModalLayout.cshtml";
}

<div class="col-md-12">
    <div class="card">
        <div class="card-header text-center">
            <img src="/images/ramgar.png" style="width: 100px; height: auto;" />
        </div>
        <div class="card-body">
            <h5>Crear Parametro </h5>
            <form asp-action="Create" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="IdUsuario" />
               

                <div class="form-group">
                    <input asp-for="Parametro" class="form-control" placeholder="Descripcion" />
                    <span asp-validation-for="Parametro" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="Valor" class="form-control" placeholder="Valor" />
                    <span asp-validation-for="Valor" class="text-danger"></span>
                </div>


                <div class="card-footer text-center">
                    <div class="form-group">
                        <button type="submit" class="btn btn-sm btn-success">
                            <i class="oi oi-check"></i>
                        </button>
                        <a href="@Url.Action("Index", "Parametros")" class="btn btn-sm btn-primary"><i class="oi oi-arrow-thick-left"></i></a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Ambe.Frontend/Ambe.Frontend/Views/Parametros/Edit.cshtml
@model Ambe.Frontend.Models.Entidades.Parametros
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/ModalLayout.cshtml";
}

<div class="col-md-12">
    <div class="card">
        <div class="card-header text-center">
            <img src="/images/ramgar.png" style="width: 100px; height: auto;" />
        </div>
        <div class="card-body">
            <h5>Editar Parametro </h5>
            <form asp-action="Edit" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="IdUsuario" />
                <input type="hidden" asp-for="IdParametro" />

                <div class="form-group">
                    <input asp-for="Parametro" class="form-control" placeholder="Descripcion" />
                    <span asp-validation-for="Parametro" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="Valor" class="form-control" placeholder="Valor" />
                    <span asp-validation-for="Valor" class="text-danger"></span>
                </div>


                <div class="card-footer text-center">
                    <div class="form-group">
                        <button type="submit" class="btn btn-sm btn-success">
                            <i class="oi oi-check"></i>
                        </button>
                        <a href="@Url.Action("Index", "Parametros")" class="btn btn-sm btn-primary"><i class="oi oi-arrow-thick-left"></i></a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Ambe.Frontend/Ambe.Frontend/Views/Parametros/Index.cshtml
@model IEnumerable<Ambe.Frontend.Models.Entidades.Parametros>
@{
    ViewData["Title"] = "Index";
}

@section Estilos {
    <link href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" rel="stylesheet" />
}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if (TempData["AlertMessage"] != null)
{
    <script>
        $(function () {
            Swal.fire({
                title: '¡Éxito!',
                text: '@TempData["AlertMessage"]',
                icon: 'success',
                confirmButtonText: 'Aceptar'
            });
        });
    </script>
}

@if (TempData["ErrorMessage"] != null)
{
    <script>
        $(function () {
            Swal.fire({
                title: '¡Error!',
                text: '@TempData["ErrorMessage"]',
                icon: 'warning',
                confirmButtonText: 'Aceptar'
            });
        });
    </script>
}

<p>
    <a onclick="showInPopup('@Url.Action("Create", "Parametros", new { id = 0 }, Context.Request.Scheme)', '')" class="btn btn-sm btn-primary text-white mt-3">
        <i class="oi oi-plus"></i> Nuevo Parametro
    </a>
</p>

<div class="col-md-12">
    <div class="card">
        <div class="card-header text-center bg-custom">
            <div class="card-header text-center">
                <img src="/images/ramgar.png" style="width: 75px; height: auto; border-radius: 50%; object-fit: cover;" />
            </div>
        </div>
        <div class="card-body">
            <h5 class="card-title text-center">Lista de Parametros</h5>
            <table id="usuario" class="table table-hover table-responsive table-striped">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Parametro</th>
                        <th scope="col">Valor</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row">@item.IdParametro</th>
                            <td>@Html.DisplayFor(modelItem => item.Parametro)</td>
                            <td>@Html.DisplayFor(modelItem => item.Valor)</td>
                            <td>
                                <a onclick="showInPopup('@Url.Action("Edit", "Parametros", new { id = item.IdParametro }, Context.Request.Scheme)', '')" class="btn btn-outline-warning btn-sm">
                                    <i class="oi oi-pencil"></i>
                                </a>
                                <button data-id="@item.IdParametro" class="btn btn-outline-danger btn-sm deleteItem">
                                    <i class="oi oi-circle-x"></i>
                                </button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<partial name="_MostrarModal" />


@section Scripts {

    <partial name="_ValidationScriptsPartial" />

    <script src="~/js/showmodal.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#usuario').DataTable({
                "language": {
                    url: "https://cdn.datatables.net/plug-ins/1.11.5/i18n/es-ES.json"
                },
            });
        });
    </script>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const deleteButtons = document.querySelectorAll('.deleteItem');

            deleteButtons.forEach(button => {
                button.addEventListener('click', function (event) {
                    event.preventDefault();

                    const patientId = this.getAttribute('data-id');


                    Swal.fire({
                        title: '¿Estás seguro?',
                        text: "¡No podrás revertir esto!",
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Sí, eliminarlo',
                        cancelButtonText: 'Cancelar'
                    }).then((result) => {
                        if (result.isConfirmed) {

                            window.location.href = '/Parametros/Delete/' + patientId;
                        }
                    });
                });
            });
        });
    </script>

}